site_name: DevStream Docs
theme: material
site_url: https://docs.devstream.io
repo_name: devstream
repo_url: https://github.com/devstream-io/devstream
site_description: The DevStream Docs
markdown_extensions:
  toc:
    permalink: true
extra_css:
- assets/versions.css
extra_javascript:
- assets/versions.js
nav:
  - 'quickstart_en.md'
  - Best Practices:
    - 'best-practices/gitops.md'
  - Commands:
    - 'commands/autocomplete.md'
    - 'commands/init.md'
    - 'commands/apply.md'
    - 'commands/verify.md'
    - 'commands/delete.md'
    - 'commands/destroy.md'
    - 'commands/develop.md'
  - Core Concepts:
    - 'core-concepts/core-concepts.md'
    - 'core-concepts/config.md'
    - 'core-concepts/variables.md'
    - 'core-concepts/stateconfig.md'
    - 'core-concepts/dependencies.md'
    - 'core-concepts/output.md'
  - Plugins:
    - 'plugins/plugins-list.md'
    - 'plugins/argocd.md'
    - 'plugins/argocdapp.md'
    - 'plugins/devlake.md'
    - 'plugins/github-repo-scaffolding-golang.md'
    - 'plugins/githubactions-golang.md'
    - 'plugins/githubactions-nodejs.md'
    - 'plugins/githubactions-python.md'
    - 'plugins/gitlab-repo-scaffolding-golang.md'
    - 'plugins/gitlabci-generic.md'
    - 'plugins/gitlabci-golang.md'
    - 'plugins/hashicorp-vault.md'
    - 'plugins/jenkins.md'
    - 'plugins/jira-github-integ.md'
    - 'plugins/kube-prometheus.md'
    - 'plugins/openldap.md'
    - 'plugins/trello.md'
    - 'plugins/trello-github-integ.md'
  - 'contribute.md'
  - Development:
    - 'development/development-workflow.md'
    - 'development/contributor_ladder_growth_programs.md'
    - 'development/project-layout.md'
    - 'development/architecture.md'
    - 'development/build.md'
    - 'development/test.md'
    - 'development/commit-messages.md'
    - 'development/lint.md'
    - 'development/creating-a-plugin.md'
    - 'development/branch-and-release.md'
  - 'troubleshooting.md'
