config:
  state:
    backend: local # backend can be local or s3
    options:
      stateFile: devstream.state

vars:
  githubUsername: daniel-hutao
  repo: go-webapp-demo

tools:
- name: repo-scaffolding
  instanceID: default
  options:
  destinationRepo:
    owner: [[ githubUsername ]]
    org: ""
    repo: [[ repo ]]
    branch: main
    repoType: github
  sourceRepo:
    org: devstream-io
    repo: dtm-repo-scaffolding-golang
    repoType: github
