config:
  state: # state config, backend can be local, s3 or k8s
    backend: local
    options:
      stateFile: devstream.state

vars:
  RepoOwner: YOUR_GITHUB_USERNAME_CASE_SENSITIVE
  ImageRepoUser: YOUR_DOCKER_USERNAME

tools:
- name: repo-scaffolding
  instanceID: golang-github
  options:
    destinationRepo:
      owner: [[ RepoOwner ]]
      name: go-webapp-devstream-demo
      branch: main
      scmType: github
    sourceRepo:
      org: devstream-io
      name: dtm-repo-scaffolding-golang-gin
      scmType: github
- name: github-actions
  instanceID: default
  dependsOn: ["repo-scaffolding.golang-github"]
  options:
    scm:
      owner: [[ RepoOwner ]]
      name: go-webapp-devstream-demo
      branch: main
      scmType: github
    pipeline:
      configLocation: https://raw.githubusercontent.com/devstream-io/dtm-pipeline-templates/main/github-actions/workflows/main.yml
      language:
        name: go
        framework: gin
      imageRepo:
        user: [[ ImageRepoUser ]]
