name: automated release
on:
  release:
    types: [published]
jobs:
  # release for linux
  build-and-release-on-linux:
    env:
      TAG: ${{ github.ref_name }}
      USER: devstream-io
      REPO: devstream
      PLUGINDIR: ~/.devstream/plugins
      GOOS: linux
      GOARCH: amd64
    runs-on: [self-hosted, linux, X64]
    steps:
      - run: echo "üêß This job is now running on a ${{ runner.os }}-${{ runner.arch }} server hosted by GitHub!"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.TAG }}
      - name: Setup Golang env
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true
      - name: Build
        run: make build -j8
      - name: Install Github-release
        run: go install github.com/github-release/github-release@latest
      - name: Install AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
          unzip -q /tmp/awscliv2.zip -d /tmp
          rm /tmp/awscliv2.zip
          sudo /tmp/aws/install --update
          rm -rf /tmp/aws/
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: upload core
        run: bash -e ./hack/release/upload_dtm_core.sh ${{ secrets.GITHUB_TOKEN }} ${{ env.TAG }} ${{ env.GOOS }} ${{ env.GOARCH }}
      - name: upload plugin
        run: aws s3 cp ~/.devstream/plugins/ s3://download.devstream.io/${{ env.TAG }}/ --recursive --acl public-read

  # release for darwin-amd64
  build-and-release-on-darwin-amd64:
    env:
      TAG: ${{ github.ref_name }}
      USER: devstream-io
      REPO: devstream
      PLUGINDIR: ~/.devstream/plugins
      GOOS: darwin
      GOARCH: amd64
    runs-on: macos-latest
    steps:
      - run: echo "üêß This job is now running on a ${{ runner.os }}-${{ runner.arch }} server hosted by GitHub!"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.TAG }}
      - name: Setup Golang env
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true
      - name: Build
        run: make build -j8
      - name: Install Github-release
        run: go install github.com/github-release/github-release@latest
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: update dtm version on s3
        run: ./hack/release/update_dtm_version_on_s3.sh ${{ env.TAG }}
      - name: upload dtm core to github release and s3
        run: bash -e ./hack/release/upload_dtm_core.sh ${{ secrets.GITHUB_TOKEN }} ${{ env.TAG }} ${{ env.GOOS }} ${{ env.GOARCH }}
      - name: upload plugins to s3
        run: aws s3 cp ~/.devstream/plugins/ s3://download.devstream.io/${{ env.TAG }}/ --recursive --acl public-read

